# Generated by Django 3.0.8 on 2020-07-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CLOSED', 'CLOSED'), ('PAUSED', 'PAUSED')], default='ACTIVE', max_length=20),
        ),
    ]
