# Generated by Django 2.1 on 2020-07-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200716_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Post date'),
        ),
    ]
